### Test inscription utilisateur
POST http://localhost:8000/auth/register
Content-Type: application/json

{
  "username": "gintokifan",
  "email": "gintoki@example.com",
  "password": "samouraï123"
}



### Connexion
POST http://localhost:8000/auth/login
Content-Type: application/json

{
  "email": "gintoki@example.com",
  "password": "samouraï123"
}

### Get current user
GET http://localhost:8000/auth/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxIiwiZXhwIjoxNzQzNTgzNjUzfQ.TkD9QAqaiPUaOPIkuWkoek8W3MeS8h4dW5EXGQvqR8c

### Ajouter ou mettre à jour une progression
POST http://localhost:8000/user/progress
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxIiwiZXhwIjoxNzQzNTg4MjYzfQ.SAfcI8OT1TRgah3oVWXT0wbyxF6QX5vnTdZixYvIzUg
Content-Type: application/json

{
  "work_id": "11061", 
  "type": "anime",
  "status": "watching",
  "current_episode": 5,
  "current_chapter": 0
}

### Récupérer la progression
GET http://localhost:8000/user/progress
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxIiwiZXhwIjoxNzQzNjA4MDk2fQ.HzpiLAPiCS-MUY7_GUEh8xMyKQj7gjz-RsZPb6oTRaU

### Supprimer une progression
DELETE http://localhost:8000/user/progress/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxIiwiZXhwIjoxNzQzNTgzNjUzfQ.TkD9QAqaiPUaOPIkuWkoek8W3MeS8h4dW5EXGQvqR8c

### Ajouter une note et un avis
POST http://localhost:8000/user/rating
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxIiwiZXhwIjoxNzQzNTg4MjYzfQ.SAfcI8OT1TRgah3oVWXT0wbyxF6QX5vnTdZixYvIzUg
Content-Type: application/json

{
  "work_id": "11061",
  "rating": 8,
  "review": "Excellent manga, bonne narration"
}

### Récupérer mes notes et avis
GET http://localhost:8000/user/rating
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxIiwiZXhwIjoxNzQzNTg4MjYzfQ.SAfcI8OT1TRgah3oVWXT0wbyxF6QX5vnTdZixYvIzUg

### Modifier une note et un avis
PUT http://localhost:8000/user/rating/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxIiwiZXhwIjoxNzQzNTg4MjYzfQ.SAfcI8OT1TRgah3oVWXT0wbyxF6QX5vnTdZixYvIzUg
Content-Type: application/json

{
  "work_id": "12345",
  "rating": 9,
  "review": "Encore meilleur à la relecture !"
}

### Supprimer une note et un avis
DELETE http://localhost:8000/user/rating/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxIiwiZXhwIjoxNzQzNTg4MjYzfQ.SAfcI8OT1TRgah3oVWXT0wbyxF6QX5vnTdZixYvIzUg

### Fiche oeuvre depuis Anilist
GET http://localhost:8000/works/11061

### Fiche oeuvre + progression
GET http://localhost:8000/works/11061
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxIiwiZXhwIjoxNzQzNzExNDAzfQ.il8XJpEdygaNL8eXrInQn9Xb1rTLHrweEWjiCTcNdX0

### Moyenne des notes
GET http://localhost:8000/works/11061
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxIiwiZXhwIjoxNzQzNTk1OTA0fQ.xQ0mPicOFpYpps3CxjwVoMMz1HMfN4_HE4_ksqPnC1A

### Recherche d’animes et de mangas
GET http://localhost:8000/works/search?search=Bleach&genre=action

### Liste des œuvres suivies par l'utilisateur connecté
GET http://localhost:8000/user/list
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxIiwiZXhwIjoxNzQzNjA4MDk2fQ.HzpiLAPiCS-MUY7_GUEh8xMyKQj7gjz-RsZPb6oTRaU

### Get recommendations limited to 4
GET http://localhost:8000/recommend
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxIiwiZXhwIjoxNzQzNjc1NDAzfQ.nJ4jEpgtGx3cOrmekWqNJP8nnlVNQTZMWJQuoI3U2Lc

### Get recommendations with a specific genre
GET http://localhost:8000/works/search?search=naruto&type=ANIME&genre=action

### toute les ouvres
GET http://localhost:8000/works/all-works
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxIiwiZXhwIjoxNzQzNzExNDAzfQ.il8XJpEdygaNL8eXrInQn9Xb1rTLHrweEWjiCTcNdX0
